### ISSUE TITLE
Pagemaster and HunterBars collision

### ISSUE THREAD

**Issue by Dinxus** [McPewPew/Bartender2-Read-Instructions#1]
Pagemaster is over hunterpages. Upon entering melee range, the bar assigned to the melee appears for a split second and then disappears. configuration changes have no effect.

**Comment by McPewPew** [comment]
I've not touched the code for these at all, they're just the last versions from 2006.  Both Pagemaster and Hunterpages work well, but sadly are not compatible with each other, you just have to pick which one you want to use.
